# Generated by Django 5.2.5 on 2025-08-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
